[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tree-sitter-mojo"
description = "Mojo grammar for tree-sitter"
version = "0.21.0"
keywords = ["parsing", "incremental", "mojo"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Topic :: Software Development :: Compilers",
  "Topic :: Text Processing :: Linguistic",
]
authors = [
  {name = "Max Brunsfeld"},
  {name = "Amaan Qureshi"}
]
requires-mojo = ">=3.8"
license.text = "MIT"
readme = "README.md"

[project.optional-dependencies]
core = ["tree-sitter~=0.21"]

[tool.cibuildwheel]
build = "cp38-*"
build-frontend = "build"
